name: theme_genius
description: A Flutter package that provides a simple way to manage theme modes in your app.
repository: https://github.com/tizianotedeschi/theme_genius
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
